package com.client.view.panel;

/**
 *
 * @author mario
 * @author alejandro
 */
public class PanelDeposito extends javax.swing.JPanel {

   /**
    * Creates new form PanelDeposito
    */
   public PanelDeposito() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize
    * the form. WARNING: Do NOT modify this code. The content of this
    * method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txtCuenta = new javax.swing.JTextField();
    txtMonto = new javax.swing.JTextField();
    btnAceptar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();

    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Ingrese los siguientes datos:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 0);
    add(jLabel1, gridBagConstraints);

    jLabel2.setText("Número de cuenta: ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    add(jLabel2, gridBagConstraints);

    jLabel3.setText("Monto a depositar: ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    add(jLabel3, gridBagConstraints);

    txtCuenta.setColumns(20);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
    add(txtCuenta, gridBagConstraints);

    txtMonto.setColumns(20);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
    add(txtMonto, gridBagConstraints);

    btnAceptar.setText("Aceptar");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    add(btnAceptar, gridBagConstraints);

    btnCancelar.setText("Cancelar");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    add(btnCancelar, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnAceptar;
  public javax.swing.JButton btnCancelar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  public javax.swing.JTextField txtCuenta;
  public javax.swing.JTextField txtMonto;
  // End of variables declaration//GEN-END:variables
}
