
package com.client.view.panel;

/**
 *
 * @author mario
 * @author alejandro
 */
public class PanelRetiro extends javax.swing.JPanel {

   /**
    * Creates new form PanelRetiro
    */
   public PanelRetiro() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize
    * the form. WARNING: Do NOT modify this code. The content of this
    * method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    btn50 = new javax.swing.JButton();
    btn100 = new javax.swing.JButton();
    btn200 = new javax.swing.JButton();
    btn500 = new javax.swing.JButton();
    btn1000 = new javax.swing.JButton();
    btn1500 = new javax.swing.JButton();
    btn2000 = new javax.swing.JButton();
    btn3000 = new javax.swing.JButton();
    btnAceptar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();
    txtMonto = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();

    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Seleccione el monto que desea retirar:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    add(jLabel1, gridBagConstraints);

    jLabel2.setText("Otra cantidad: El monto debe ser multiplo de 50.");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
    add(jLabel2, gridBagConstraints);

    btn50.setText("$50.00");
    btn50.setMaximumSize(new java.awt.Dimension(200, 30));
    btn50.setMinimumSize(new java.awt.Dimension(100, 20));
    btn50.setPreferredSize(new java.awt.Dimension(170, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btn50, gridBagConstraints);

    btn100.setText("$100.00");
    btn100.setMaximumSize(new java.awt.Dimension(200, 30));
    btn100.setMinimumSize(new java.awt.Dimension(100, 20));
    btn100.setPreferredSize(new java.awt.Dimension(170, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btn100, gridBagConstraints);

    btn200.setText("$200.00");
    btn200.setMaximumSize(new java.awt.Dimension(200, 30));
    btn200.setMinimumSize(new java.awt.Dimension(100, 20));
    btn200.setPreferredSize(new java.awt.Dimension(170, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btn200, gridBagConstraints);

    btn500.setText("$500.00");
    btn500.setMaximumSize(new java.awt.Dimension(200, 30));
    btn500.setMinimumSize(new java.awt.Dimension(100, 20));
    btn500.setPreferredSize(new java.awt.Dimension(170, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btn500, gridBagConstraints);

    btn1000.setText("$1000.00");
    btn1000.setMaximumSize(new java.awt.Dimension(200, 30));
    btn1000.setMinimumSize(new java.awt.Dimension(100, 20));
    btn1000.setPreferredSize(new java.awt.Dimension(170, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btn1000, gridBagConstraints);

    btn1500.setText("$1500.00");
    btn1500.setMaximumSize(new java.awt.Dimension(200, 30));
    btn1500.setMinimumSize(new java.awt.Dimension(100, 20));
    btn1500.setPreferredSize(new java.awt.Dimension(170, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btn1500, gridBagConstraints);

    btn2000.setText("$2000.00");
    btn2000.setMaximumSize(new java.awt.Dimension(200, 30));
    btn2000.setMinimumSize(new java.awt.Dimension(100, 20));
    btn2000.setPreferredSize(new java.awt.Dimension(170, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btn2000, gridBagConstraints);

    btn3000.setText("$3000.00");
    btn3000.setMaximumSize(new java.awt.Dimension(200, 30));
    btn3000.setMinimumSize(new java.awt.Dimension(100, 20));
    btn3000.setPreferredSize(new java.awt.Dimension(170, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btn3000, gridBagConstraints);

    btnAceptar.setText("Aceptar");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    add(btnAceptar, gridBagConstraints);

    btnCancelar.setText("Cancelar");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    add(btnCancelar, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(txtMonto, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jSeparator1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btn100;
  public javax.swing.JButton btn1000;
  public javax.swing.JButton btn1500;
  public javax.swing.JButton btn200;
  public javax.swing.JButton btn2000;
  public javax.swing.JButton btn3000;
  public javax.swing.JButton btn50;
  public javax.swing.JButton btn500;
  public javax.swing.JButton btnAceptar;
  public javax.swing.JButton btnCancelar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JSeparator jSeparator1;
  public javax.swing.JTextField txtMonto;
  // End of variables declaration//GEN-END:variables
}
