
package com.client.view.panel;

/**
 *
 * @author mario
 */
public class PanelRetiro extends javax.swing.JPanel {

   /**
    * Creates new form PanelRetiro
    */
   public PanelRetiro() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize
    * the form. WARNING: Do NOT modify this code. The content of this
    * method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      btn50 = new javax.swing.JButton();
      btn100 = new javax.swing.JButton();
      btn200 = new javax.swing.JButton();
      btn500 = new javax.swing.JButton();
      btn1000 = new javax.swing.JButton();
      btn1500 = new javax.swing.JButton();
      btn2000 = new javax.swing.JButton();
      btn3000 = new javax.swing.JButton();
      jLabel2 = new javax.swing.JLabel();
      txtMonto = new javax.swing.JTextField();
      btnAceptar = new javax.swing.JButton();
      btnCancelar = new javax.swing.JButton();
      jSeparator1 = new javax.swing.JSeparator();

      jLabel1.setText("Seleccione el monto que desea retirar:");

      btn50.setText("$50.00");
      btn50.setMaximumSize(new java.awt.Dimension(200, 30));
      btn50.setMinimumSize(new java.awt.Dimension(100, 20));
      btn50.setPreferredSize(new java.awt.Dimension(170, 25));

      btn100.setText("$100.00");
      btn100.setMaximumSize(new java.awt.Dimension(200, 30));
      btn100.setMinimumSize(new java.awt.Dimension(100, 20));
      btn100.setPreferredSize(new java.awt.Dimension(170, 25));

      btn200.setText("$200.00");
      btn200.setMaximumSize(new java.awt.Dimension(200, 30));
      btn200.setMinimumSize(new java.awt.Dimension(100, 20));
      btn200.setPreferredSize(new java.awt.Dimension(170, 25));

      btn500.setText("$500.00");
      btn500.setMaximumSize(new java.awt.Dimension(200, 30));
      btn500.setMinimumSize(new java.awt.Dimension(100, 20));
      btn500.setPreferredSize(new java.awt.Dimension(170, 25));

      btn1000.setText("$1000.00");
      btn1000.setMaximumSize(new java.awt.Dimension(200, 30));
      btn1000.setMinimumSize(new java.awt.Dimension(100, 20));
      btn1000.setPreferredSize(new java.awt.Dimension(170, 25));

      btn1500.setText("$1500.00");
      btn1500.setMaximumSize(new java.awt.Dimension(200, 30));
      btn1500.setMinimumSize(new java.awt.Dimension(100, 20));
      btn1500.setPreferredSize(new java.awt.Dimension(170, 25));

      btn2000.setText("$2000.00");
      btn2000.setMaximumSize(new java.awt.Dimension(200, 30));
      btn2000.setMinimumSize(new java.awt.Dimension(100, 20));
      btn2000.setPreferredSize(new java.awt.Dimension(170, 25));

      btn3000.setText("$3000.00");
      btn3000.setMaximumSize(new java.awt.Dimension(200, 30));
      btn3000.setMinimumSize(new java.awt.Dimension(100, 20));
      btn3000.setPreferredSize(new java.awt.Dimension(170, 25));

      jLabel2.setText("Otra cantidad: El monto debe ser multiplo de 50.");

      btnAceptar.setText("Aceptar");

      btnCancelar.setText("Cancelar");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(20, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jSeparator1)
               .addComponent(txtMonto)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(btn200, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btn100, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btn50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btn500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(btn1000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btn2000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btn3000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btn1500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(20, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(15, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn1500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn2000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn3000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnCancelar)
               .addComponent(btnAceptar))
            .addContainerGap(20, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   public javax.swing.JButton btn100;
   public javax.swing.JButton btn1000;
   public javax.swing.JButton btn1500;
   public javax.swing.JButton btn200;
   public javax.swing.JButton btn2000;
   public javax.swing.JButton btn3000;
   public javax.swing.JButton btn50;
   public javax.swing.JButton btn500;
   public javax.swing.JButton btnAceptar;
   public javax.swing.JButton btnCancelar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JSeparator jSeparator1;
   public javax.swing.JTextField txtMonto;
   // End of variables declaration//GEN-END:variables
}
