package com.client.view.panel;

/**
 *
 * @author mario
 * @author alejandro
 */
public class PanelConsulta extends javax.swing.JPanel {

   /**
    * Creates new form PanelConsulta
    */
   public PanelConsulta() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize
    * the form. WARNING: Do NOT modify this code. The content of this
    * method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    lblSaldo = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Su saldo es: ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
    add(jLabel1, gridBagConstraints);

    lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblSaldo.setText("$ XXXXX. XX MNM");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
    add(lblSaldo, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  public javax.swing.JLabel lblSaldo;
  // End of variables declaration//GEN-END:variables
}
