package com.client.view;

/**
 *
 * @author mario
 * @author alejandro
 */
public class Principal extends javax.swing.JFrame {

   /**
    * Creates new form Principal
    */
   public Principal() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jToolBar1 = new javax.swing.JToolBar();
      btnConsulta = new javax.swing.JButton();
      btnRetiro = new javax.swing.JButton();
      btnDeposito = new javax.swing.JButton();
      btnTransferencia = new javax.swing.JButton();
      btnCerrar = new javax.swing.JButton();
      dpPrincipal = new javax.swing.JDesktopPane();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jToolBar1.setRollover(true);

      btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/consulta.png"))); // NOI18N
      btnConsulta.setText("Consulta de saldo");
      btnConsulta.setFocusable(false);
      btnConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnConsulta.setPreferredSize(new java.awt.Dimension(130, 80));
      btnConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      jToolBar1.add(btnConsulta);

      btnRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Retiro.png"))); // NOI18N
      btnRetiro.setText("Retiro de efectivo");
      btnRetiro.setFocusable(false);
      btnRetiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnRetiro.setPreferredSize(new java.awt.Dimension(130, 80));
      btnRetiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      jToolBar1.add(btnRetiro);

      btnDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/deposito.png"))); // NOI18N
      btnDeposito.setText("Depósito");
      btnDeposito.setFocusable(false);
      btnDeposito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnDeposito.setPreferredSize(new java.awt.Dimension(130, 80));
      btnDeposito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      jToolBar1.add(btnDeposito);

      btnTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/transferencia.png"))); // NOI18N
      btnTransferencia.setText("Transferencia");
      btnTransferencia.setFocusable(false);
      btnTransferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnTransferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      jToolBar1.add(btnTransferencia);

      btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salir.png"))); // NOI18N
      btnCerrar.setText("Cerrar");
      btnCerrar.setFocusable(false);
      btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      jToolBar1.add(btnCerrar);

      getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);
      getContentPane().add(dpPrincipal, java.awt.BorderLayout.CENTER);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   // Variables declaration - do not modify//GEN-BEGIN:variables
   public javax.swing.JButton btnCerrar;
   public javax.swing.JButton btnConsulta;
   public javax.swing.JButton btnDeposito;
   public javax.swing.JButton btnRetiro;
   public javax.swing.JButton btnTransferencia;
   public javax.swing.JDesktopPane dpPrincipal;
   private javax.swing.JToolBar jToolBar1;
   // End of variables declaration//GEN-END:variables
}
