package com.client.view;

/**
 *
 * @author mario
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

   /**
    * Creates new form VentanaInterna
    */
   public VentanaInterna() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setClosable(true);
      setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
      setMaximizable(true);
      setResizable(true);
      setAutoscrolls(true);
      setMinimumSize(new java.awt.Dimension(40, 32));
      setVisible(false);

      pack();
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
